import Head from "next/head";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HopeSetting from "@/components/HopeSettingFrame";
import SelectClassFrame from "@/components/SelectClassFrame";
import ShowOperatorFrame from "@/components/ShowOperatorFrame";
import { useState } from "react";
import { ClassType } from "@/components/ClassType";
import ChooseButton, { Operator } from "@/components/ChooseButton";

export default function Home() {
  const [initialHope, setInitialHope] = useState<number>(0);
  const [rankHopeCosts, setHopeCosts] = useState<number[]>([0, 0, 0, 0, 0, 0]);
  const [selectedClass, setSelectedClass] = useState<ClassType[]>([
    ClassType.Vanguard,
    ClassType.Vanguard,
    ClassType.Vanguard,
  ]);
  const [selectedOperators, setSelectedOperators] = useState<Operator[]>([]);

  return (
    <>
      <Head>
        <title>Choose Me! Doctor♡</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" className="py-4 px-3 mx-auto" style={{ minWidth: "800px", maxWidth: "800px" }}>
        <Header />
        <HopeSetting
          setInitialHope={setInitialHope}
          setHopeCosts={setHopeCosts}
        />
        <SelectClassFrame setSelectedClass={setSelectedClass} />
        <ChooseButton
          initialHope={initialHope}
          rankHopeCosts={rankHopeCosts}
          selectedClass={selectedClass}
          setSelectedOperators={setSelectedOperators}
        />
        <ShowOperatorFrame
          selectedOperators={selectedOperators}
        />
        <Footer />
      </Container>
    </>
  );
}